[profile.default]
src = "src"
test = "test"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
threads = 1
broadcast = "broadcast"
eth_send_raw_tx = true
script_execution_protection = false
fs_permissions = [
  { access = "read", path = "./proof" },
  { access = "read", path = "." }      # optional
]

[profile.default.wallets]
from = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"


[rpc_endpoints]
local = "http://127.0.0.1:8545"
